#!/usr/bin/env python3
"""
MOSTARDA — Gerador de Chaves para Ambiente de Teste (Devnet/Testnet)

Gera automaticamente:
  1. Par de chaves Stellar (Testnet) — Keypair.random() + Friendbot funding
  2. Par de chaves Solana (Devnet) — Keypair() + request_airdrop

Saída: .env.dev  (pronto para usar com docker-compose ou dotenv)

Uso:
  python scripts/generate_test_keys.py          # Gera e salva
  python scripts/generate_test_keys.py --show   # Apenas exibe, não salva
  python scripts/generate_test_keys.py --fund   # Gera + funde via Friendbot/Airdrop
"""

import argparse
import os
import sys
from pathlib import Path


# Paths
SCRIPT_DIR = Path(__file__).parent.resolve()
PROJECT_DIR = SCRIPT_DIR.parent
ENV_DEV_PATH = PROJECT_DIR / ".env.dev"

# Stellar Testnet
STELLAR_HORIZON = "https://horizon-testnet.stellar.org"
STELLAR_FRIENDBOT = "https://friendbot.stellar.org"
STELLAR_NETWORK = "Test SDF Network ; September 2015"

# Solana Devnet
SOLANA_RPC = "https://api.devnet.solana.com"
SOLANA_AIRDROP_AMOUNT = 2_000_000_000  # 2 SOL em lamports


def banner(text: str):
    print()
    print("=" * 60)
    print(f"  {text}")
    print("=" * 60)


def generate_stellar_keypair() -> dict:
    """Generate a random Stellar keypair and optionally fund via Friendbot."""
    try:
        from stellar_sdk import Keypair
    except ImportError:
        print("❌ stellar-sdk not installed. Run: pip install stellar-sdk requests")
        sys.exit(1)

    banner("🌐 Gerando chave Stellar Testnet")
    keypair = Keypair.random()
    print(f"  Public Key:  {keypair.public_key}")
    print(f"  Secret Seed: {keypair.secret}")
    print(f"  Horizon:     {STELLAR_HORIZON}")
    print(f"  Network:     {STELLAR_NETWORK}")
    return {
        "public": keypair.public_key,
        "secret": keypair.secret,
    }


def fund_stellar(public_key: str) -> bool:
    """Fund a Stellar Testnet account via Friendbot."""
    import requests
    try:
        print(f"\n  ⏳ Funding Stellar account {public_key[:16]}... via Friendbot...")
        resp = requests.get(
            STELLAR_FRIENDBOT,
            params={"addr": public_key},
            timeout=30,
        )
        if resp.status_code == 200:
            data = resp.json()
            hash_tx = data.get("hash", "unknown")
            print(f"  ✅ Stellar funded! TX hash: {hash_tx[:16]}...")
            return True
        else:
            print(f"  ⚠️ Stellar funding returned HTTP {resp.status_code}: {resp.text[:100]}")
            return False
    except requests.RequestException as e:
        print(f"  ⚠️ Stellar funding error (network may be down): {e}")
        return False


def generate_solana_keypair() -> dict:
    """Generate a random Solana keypair."""
    try:
        from solders.keypair import Keypair
    except ImportError:
        print("❌ solders not installed. Run: pip install solana solders")
        sys.exit(1)

    banner("🌐 Gerando chave Solana Devnet")
    keypair = Keypair()
    pubkey = str(keypair.pubkey())
    secret_bytes = bytes(keypair)
    secret_hex = secret_bytes.hex()

    print(f"  Public Key:  {pubkey}")
    print(f"  Secret Key:  {secret_hex[:32]}... (hex)")
    print(f"  RPC:         {SOLANA_RPC}")
    return {
        "public": pubkey,
        "secret_hex": secret_hex,
    }


async def fund_solana(public_key: str) -> bool:
    """Fund a Solana Devnet account via airdrop."""
    try:
        from solana.rpc.async_api import AsyncClient
        from solders.pubkey import Pubkey
    except ImportError:
        print("  ⚠️ solana-py not installed. Skipping funding.")
        return False

    try:
        pubkey_obj = Pubkey.from_string(public_key)
        async with AsyncClient(SOLANA_RPC) as client:
            print(f"\n  ⏳ Requesting airdrop of {SOLANA_AIRDROP_AMOUNT / 1_000_000_000} SOL to {public_key[:16]}...")
            resp = await client.request_airdrop(pubkey_obj, SOLANA_AIRDROP_AMOUNT)
            tx_sig = resp.value
            print(f"  ⏳ Confirming transaction {str(tx_sig)[:16]}...")
            await client.confirm_transaction(tx_sig, commitment="confirmed")
            balance = await client.get_balance(pubkey_obj)
            sol = balance.value / 1_000_000_000
            print(f"  ✅ Solana funded! Balance: {sol:.2f} SOL")
            return True
    except Exception as e:
        print(f"  ⚠️ Solana funding error: {e}")
        return False


def write_env(
    stellar: dict,
    solana: dict,
    funded: bool,
    stellar_funded: bool,
    solana_funded: bool,
):
    """Write .env.dev file with all configuration."""
    lines = [
        "# ── MOSTARDA Dev Environment (auto-generated) ─────",
        "# Generated by: scripts/generate_test_keys.py",
        "# DO NOT use these keys in production! Testnet only.",
        "",
        "# App",
        "APP_NAME=mostarda-backend",
        "APP_VERSION=1.0.0",
        "DEBUG=true",
        f"SECRET_KEY={os.urandom(32).hex()}",
        "ACCESS_TOKEN_EXPIRE_MINUTES=60",
        "REFRESH_TOKEN_EXPIRE_DAYS=7",
        "",
        "# Database",
        "DATABASE_URL=postgresql+asyncpg://mostarda:mostarda@db:5432/mostarda",
        "DATABASE_URL_SYNC=postgresql+psycopg2://mostarda:mostarda@db:5432/mostarda",
        "",
        "# PSAV (configure manualmente para testes reais)",
        "PSAV_PROVIDER=depix",
        "PSAV_API_KEY=",
        "PSAV_API_SECRET=",
        "PSAV_WEBHOOK_SECRET=dev_webhook_secret_change_me",
        "PSAV_STABLECOIN=BRLX",
        "",
        "# Settlement",
        "SETTLEMENT_WEEKLY_DAYS=7",
        "SETTLEMENT_MONTHLY_DAYS=30",
        "",
        "# Blockchain — Stellar Testnet",
        f"STELLAR_HORIZON_URL={STELLAR_HORIZON}",
        f"STELLAR_NETWORK_PASSPHRASE={STELLAR_NETWORK}",
        f"STELLAR_DISTRIBUTION_SEED={stellar['secret']}",
        "STELLAR_ASSET_CODE=BRLX",
        f"# Stellar Public Key: {stellar['public']}",
        f"# Stellar Funded: {'YES' if stellar_funded else 'NO (manual funding required)'}",
        "",
        "# Blockchain — Solana Devnet",
        f"SOLANA_RPC_URL={SOLANA_RPC}",
        "SOLANA_PROGRAM_ID=",
        f"# Solana Public Key: {solana['public']}",
        f"# Solana Secret (hex): {solana['secret_hex'][:32]}...",
        f"# Solana Funded: {'YES' if solana_funded else 'NO (manual airdrop required)'}",
        "",
        "# Blockchain Config",
        "BLOCKCHAIN_FEE_THRESHOLD_XLM=0.001",
        "BLOCKCHAIN_CIRCUIT_COOLDOWN_SECONDS=300",
        "",
        "# DeFi Yield",
        "YIELD_POOL_ADDRESS=",
        "YIELD_POOL_PROTOCOL=aave",
        "YIELD_MIN_HOLD_HOURS=24",
        "",
        "# Telemetry",
        "AUDIENCE_CONFIDENCE_THRESHOLD=0.5",
        "PROXIMITY_RSSI_THRESHOLD=-70",
        "",
        "# Rate Limiting",
        "RATE_LIMIT_WINDOW=60",
        "RATE_LIMIT_MAX_ATTEMPTS=10",
    ]

    ENV_DEV_PATH.write_text("\n".join(lines) + "\n")
    print(f"\n  ✅ Written to {ENV_DEV_PATH}")


async def main():
    parser = argparse.ArgumentParser(description="Generate test keys for Stellar Testnet + Solana Devnet")
    parser.add_argument("--show", action="store_true", help="Only display keys, don't save")
    parser.add_argument("--fund", action="store_true", help="Fund accounts via Friendbot/Airdrop")
    args = parser.parse_args()

    print()
    print("🍅 MOSTARDA — Gerador de Chaves de Teste")
    print("  Stellar Testnet + Solana Devnet")

    # Generate keys
    stellar = generate_stellar_keypair()
    solana = generate_solana_keypair()

    # Funding (optional)
    funded = args.fund
    stellar_funded = False
    solana_funded = False

    if funded:
        banner("💰 Fundindo contas de teste")
        stellar_funded = fund_stellar(stellar["public"])
        import asyncio
        solana_funded = await fund_solana(solana["public"])

    if args.show:
        banner("📋 Chaves geradas (não salvas)")
        print(f"\nStellar:")
        print(f"  STELLAR_DISTRIBUTION_SEED={stellar['secret']}")
        print(f"  (public: {stellar['public']})")
        print(f"\nSolana:")
        print(f"  SOLANA_SECRET={solana['secret_hex']}")
        print(f"  (public: {solana['public']})")
        return

    # Write .env.dev
    banner("📝 Salvando .env.dev")
    write_env(stellar, solana, funded, stellar_funded, solana_funded)

    print()
    print("  🚀 Para iniciar o ambiente:")
    print("    docker compose up -d --build")
    print()
    print("  ℹ️  Para carregar sem Docker:")
    print(f"    cp {ENV_DEV_PATH} .env")
    print("    uvicorn main:app --reload")
    print()


if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
