#!/bin/bash
# Guia de migração Convex → Supabase
echo "═══════════════════════════════════"
echo "  Migração Convex → Supabase"
echo "═══════════════════════════════════"
echo ""
echo "Passo 1: Despejar dados do Convex"
echo "  npx convex export"
echo ""
echo "Passo 2: Converter para SQL"
echo "  node scripts/convert-to-sql.js"
echo ""
echo "Passo 3: Importar para Supabase"
echo "  docker exec -i mostarda-db psql -U postgres -d mostarda < dados.sql"
echo ""
echo "Passo 4: Verificar"
echo "  docker exec mostarda-db psql -U postgres -d mostarda -c"
echo "  "SELECT count(*) FROM users;""
